package com.Brocamp;

import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

public class May12FindTheDifference {

//    389. Find the Difference

//    You are given two strings s and t.
//
//    String t is generated by random shuffling string s and then add one more letter at a random position.
//
//    Return the letter that was added to t.
//
//
//
//    Example 1:
//
//    Input: s = "abcd", t = "abcde"
//    Output: "e"
//    Explanation: 'e' is the letter that was added.
//    Example 2:
//
//    Input: s = "", t = "y"
//    Output: "y"

    public static void main(String[] args) {

        String firstString = "abcd", t = "abcde";

        findTheDifference(firstString, t);

    }

    public static void findTheDifference(String firstString, String t) {

        Set<Character> set = new HashSet<>();

        for (char c : firstString.toCharArray()) {
            set.add(c);
        }

        for (char c : t.toCharArray()) {
            if (!set.contains(c)) {
                System.out.println(c);
            }
        }
    }

    public static void findTheDifferenceStream(String firstString, String t) {


        Set<Character> characterSet = firstString.chars().mapToObj(c -> (char) c).collect(Collectors.toCollection(HashSet::new));

        t.chars().filter(c -> !characterSet.contains(c)).forEach(System.out::println);
    }
}
